### ISSUE TITLE
Duplicated buttons in top panel

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-grapesjs#3]
**Environment:**
Jmix version: 0.9.0
IntelliJ version: IntelliJ IDEA 2020.3.3 (Community Edition)

### Descriptions of the bug:
1. Create custom theme and add theme-property file to resources
2. Add dependencies and reload gradle project
```
implementation 'io.jmix.grapesjs:jmix-grapesjs-starter'
themes 'io.jmix.ui:jmix-ui-themes'
themes 'io.jmix.grapesjs:jmix-grapesjs'
```
3. Create the screen with HTML Editor 
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<window xmlns="http://jmix.io/schema/ui/window"
        caption="msg://newScreen.caption"
        xmlns:et="http://jmix.io/schema/grapesjs/ui">
    <layout>
        <et:grapesJsWebpageHtmlEditor id="htmlEditor">
            <et:disabledBlocks>
                map,tabs
            </et:disabledBlocks>
        </et:grapesJsWebpageHtmlEditor>
    </layout>
</window>
```
4. Run application
5. Open created screen

**ER:** each button on the top panel is unique
**AR:** some buttons on the top panel are duplicated
![image](https://user-images.githubusercontent.com/69783839/112632589-be3b8900-8e51-11eb-9b2e-3837eb645b7c.png)

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT -verified
